//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int Customer_Id { get; set; }
        public string NIC { get; set; }
        public string Fname { get; set; }
        public string Lname { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Phone { get; set; }
        public string Customer_Status { get; set; }
        public string Title { get; set; }
        public Nullable<double> Due_Balance { get; set; }
        public byte[] Create_At { get; set; }
        public string Remote_Action { get; set; }
        public string Customer1 { get; set; }
    }
}
