//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice_Item
    {
        public Nullable<double> Item_Sell_Price { get; set; }
        public Nullable<int> Item_Quantity { get; set; }
        public byte[] Create_At { get; set; }
        public string Remote_Action { get; set; }
        public int Item_Id { get; set; }
        public int Invoice_Id { get; set; }
        public string Invoice_Item1 { get; set; }
    }
}
