//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int Invoice_Id { get; set; }
        public string Next_Payment { get; set; }
        public Nullable<double> Total_Bill_Price { get; set; }
        public Nullable<double> Sale_Type { get; set; }
        public string Sale_Status { get; set; }
        public string Sale_Ref_ID { get; set; }
        public Nullable<double> Bill_Discount { get; set; }
        public Nullable<System.DateTime> Due_Date { get; set; }
        public byte[] Create_At { get; set; }
        public string Remote_Action { get; set; }
        public int User_Id { get; set; }
        public int Customer_Id { get; set; }
        public string Invoice1 { get; set; }
    }
}
