//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int Item_Id { get; set; }
        public string Item_Name { get; set; }
        public Nullable<double> Retail_Price { get; set; }
        public Nullable<double> Retail_Discount { get; set; }
        public Nullable<int> Unit { get; set; }
        public string Category { get; set; }
        public string Sub_Category { get; set; }
        public string Min_Stock { get; set; }
        public Nullable<int> Stock_Quantity { get; set; }
        public Nullable<double> label_Price { get; set; }
        public string Barcode { get; set; }
        public Nullable<double> Wholesale_Price { get; set; }
        public Nullable<double> Wholesale_Discount { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Stock_Updated_At { get; set; }
        public string Remote_Action { get; set; }
        public int Sub_Category_Id { get; set; }
        public string Item1 { get; set; }
    }
}
