//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBEntities : DbContext
    {
        public DBEntities()
            : base("name=DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Customer_Phone> Customer_Phone { get; set; }
        public virtual DbSet<Discount_Card> Discount_Card { get; set; }
        public virtual DbSet<Invoice> Invoices { get; set; }
        public virtual DbSet<Invoice_Item> Invoice_Item { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<Overdue_Invoice> Overdue_Invoice { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<Regular_Invoice> Regular_Invoice { get; set; }
        public virtual DbSet<Sub_Category> Sub_Category { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<Supplier_Item> Supplier_Item { get; set; }
        public virtual DbSet<Supplier_Phone> Supplier_Phone { get; set; }
        public virtual DbSet<Supplier_Stock> Supplier_Stock { get; set; }
        public virtual DbSet<Supplier_Stock_Item> Supplier_Stock_Item { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
