//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Overdue_Invoice
    {
        public int Invoice_Id { get; set; }
        public Nullable<System.DateTime> Invoice_Date { get; set; }
        public Nullable<double> Stock_Discount { get; set; }
        public string Overdue_Invoice1 { get; set; }
    }
}
