//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int Payment_Id { get; set; }
        public string Payment_Type { get; set; }
        public Nullable<double> Amount { get; set; }
        public byte[] Create_At { get; set; }
        public string Remote_Action { get; set; }
        public int Invoice_id { get; set; }
        public string Payment1 { get; set; }
    }
}
