//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Regular_Invoice
    {
        public int Invoice_Id { get; set; }
        public Nullable<double> Paid_Amount { get; set; }
        public string Regular_Invoice1 { get; set; }
    }
}
