//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sub_Category
    {
        public int Sub_Category_Id { get; set; }
        public string Sub_Category_Name { get; set; }
        public string Category_Status { get; set; }
        public byte[] Create_At { get; set; }
        public string Remote_Action { get; set; }
        public int Category_Id { get; set; }
        public string Sub_Category1 { get; set; }
    }
}
