//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier_Stock
    {
        public int SS_ID { get; set; }
        public int Invoice_No { get; set; }
        public Nullable<System.DateTime> Invoice_Date { get; set; }
        public Nullable<double> Stock_Total_Price { get; set; }
        public Nullable<double> Stock_Discount { get; set; }
        public byte[] Create_At { get; set; }
        public string Remote_Action { get; set; }
        public int Supplier_Id { get; set; }
        public string Supplier_Stock1 { get; set; }
    }
}
