//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier_Stock_Item
    {
        public int Supplier_Invoice_No { get; set; }
        public string Item_Ref_Id { get; set; }
        public Nullable<int> Item_Stock { get; set; }
        public Nullable<double> Item_Buying_Price { get; set; }
        public Nullable<int> Buying_Stock { get; set; }
        public Nullable<double> Buying_Discount { get; set; }
        public byte[] Create_At { get; set; }
        public string Remote_Action { get; set; }
        public int SS_Id { get; set; }
        public int Item_Id { get; set; }
        public string Supplier_Stock_Item1 { get; set; }
    }
}
