//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        public int Supplier_Id { get; set; }
        public string Supplier_Name { get; set; }
        public string Supplier_Company { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Status { get; set; }
        public byte[] Create_At { get; set; }
        public string Remote_Action { get; set; }
        public string Supplier1 { get; set; }
    }
}
